version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=StockHarbor
      - POSTGRES_PASSWORD=StockHarborPassword
      - POSTGRES_DB=StockHarbor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: